services:
  claude-code-router:
    container_name: claude-code-router
    build:
      context: .
    ports:
      - "${CCR_HOST_PORT:-9003}:3456"
    volumes:
      - ~/.claude-code-router:/root/.claude-code-router
    env_file:
      - .env
    environment:
      # Set your API key for UI authentication
      # This APIKEY will be used to protect both the UI and API endpoints
      - APIKEY=${APIKEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
